version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: "circleci/openjdk:8"
    steps:
      - checkout
      - run: tar zcvf assets.tar.gz assets
      - store_artifacts:
          path: assets.tar.gz
          destination: assets.tar.gz
      - run: "export ARTIFACT=$(curl -f -u $CIRCLE_TOKEN: https://circleci.com/api/v1.1/project/github/phoebus-games/$COMPONENT/$COMPONENT_BUILD_NUM/artifacts|jq '.[] | .url')"
      - run: "curl -fv -u $CIRCLE_TOKEN: -X POST -d '{\"build_parameters\": {\"ARTIFACT\": \"$ARTIFACT\"}}' -H 'Content-Type: application/json' https://circleci.com/api/v1.1/project/github/phoebus-games/deploy-assets/tree/master"
